# Generated by Django 5.2.8 on 2025-11-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payroll',
            old_name='basic_salary',
            new_name='basic_pay',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='deductions',
            new_name='bonus',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='net_pay',
            new_name='total_pay',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10),
        ),
    ]
